import Logo from "./components/Logo";
import Navigation from "./components/navigation";

export const metadata = {
  title: "The Wood Heaven",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
